kind: pipeline
name: default

steps:
  - name: build
    image: tianon/latex
    commands:
      - pdflatex --interaction=errorstopmode -output-directory dist RohitGohri.tex

  - name: release
    image: plugins/github-release
    settings:
      api_key:
        from_secret: github_token
      files: 
        - dist/RohitGohri.pdf
        - RohitGohri.pdf
    when:
      event: tag

...