---
# https://manpages.ubuntu.com/manpages/bionic/man1/pdflatex.1.html
kind: pipeline
name: release

steps:
  - name: update on site
    image: plugins/downstream
    settings:
      server: https://cloud.drone.io
      token:
        from_secret: drone_token
      fork: true
      last_successful: true
      deploy: resume
      repositories:
        - rohit-gohri/rohit-gohri.github.io@master
        - rohit-gohri/blog@master

trigger:
  event: tag
