kind: pipeline
name: default

steps:
  - name: build
    image: tianon/latex
    commands:
      - pdflatex cv.tex -output-directory dist

  - name: release
    image: plugins/github-release
    settings:
      api_key:
        from_secret: github_token
      files: ./dist/cv.pdf

triggers:
  event: tag
...