name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Add private content
        env:
          PRIVATE_CONTENT: ${{ secrets.PRIVATE_CONTENT }}
        run: |
          echo $PRIVATE_CONTENT > RohitGohri.tmp

      - name: Generate PDF
        uses: xu-cheng/latex-action@master
        with:
          root_file: |
            resume.tex
          args: |
            -pdf -interaction=nonstopmode -halt-on-error -jobname=RohitGohri

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: RohitGohri.pdf
          tag_name: ${{ github.ref }}
          name: Release ${{ github.ref }}
          draft: false
          prerelease: false
